apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: todo-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: todo-backend
